<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>
            項目
        </th>
        <th>
            加價
        </th>
        <th>
            說明
        </th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            最新消息/部落格
        </td>
        <td>
            $4,000
        </td>
        <td>
            提供友善閱讀的部落格/訊息展示方式，將內容給更多客戶/粉絲看到。
        </td>
    </tr>
    <tr>
        <td>
            留言版
        </td>
        <td>
            $4,000
        </td>
        <td>
            流水線式的留言板，管理員可逐篇一一回覆，適合簡易快速的問答。
        </td>
    </tr>
    <tr>
        <td>
            友好連結/合作廠商
        </td>
        <td>
            $3,000
        </td>
        <td>
            新增友好網站或合作廠商網址連結與分類。
        </td>
    </tr>
    <tr>
        <td>
            相簿藝廊
        </td>
        <td>
            $4,000
        </td>
        <td>
            顯示圖片用的相簿藝廊，亦可設定圖片分類。
        </td>
    </tr>
    <tr>
        <td>
            人才招募
        </td>
        <td>
            $4,000
        </td>
        <td>
            較複雜的徵才功能，可區分部門、職務，並填入完整職務介紹與薪資等等。
        </td>
    </tr>
    <tr>
        <td>
            員工介紹
        </td>
        <td>
            $4,000
        </td>
        <td>
            可區分部門、院系或各種分類，介紹成員並上傳專屬照片。
        </td>
    </tr>
    <tr>
        <td>
            檔案下載
        </td>
        <td>
            $5,000
        </td>
        <td>
            具備多重分類，支援各種檔案類型的下載功能。
        </td>
    </tr>
    <tr>
        <td>
            線上影音
        </td>
        <td>
            $6,000
        </td>
        <td>
            線上影音目錄，可崁入Youtube或Vimeo等服務。
        </td>
    </tr>
    <tr>
        <td>
            多人共筆部落格
        </td>
        <td>
            $8,000
        </td>
        <td>
            支援多作者、群組部落格，提供註冊後成為網站專欄作家。
        </td>
    </tr>
    <tr>
        <td>
            Q&amp;A問題集系統
        </td>
        <td>
            $6,000
        </td>
        <td>
            相似奇摩知識+形式的公眾問答工具，含討論功能，適合客服人員使用。
        </td>
    </tr>
    <tr>
        <td>
            線上行事曆
        </td>
        <td>
            $7,000
        </td>
        <td>
            已月曆型式記錄各類型活動，亦可同步至Facebook活動或Google行事曆。
        </td>
    </tr>
    <tr>
        <td>
            報名系統
        </td>
        <td>
            $6,000
        </td>
        <td>
            提供自定欄位功能，供外部人員報名。
        </td>
    </tr>
    <tr>
        <td>
            商品型錄
        </td>
        <td>
            $6,000
        </td>
        <td>
            提供線上商品圖文展示，並可詢價
        </td>
    </tr>
    <tr>
        <td>
            多功能聯絡表單
        </td>
        <td>
            $4,000
        </td>
        <td>
            可自訂聯絡我們的表單欄位
        </td>
    </tr>
    <tr>
        <td>
            分店資訊
        </td>
        <td>
            $6,000
        </td>
        <td>
            可提供多間店面查詢與營業資訊等
        </td>
    </tr>
    <tr>
        <td>
            社群登入
        </td>
        <td>
            $5,000
        </td>
        <td>
            Facebook, Google 等登入功能
        </td>
    </tr>
    </tbody>
</table>