<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th width="20%">
            <strong>項目</strong>
        </th>
        <th width="10%">
            <strong>加價</strong>
        </th>
        <th>
            <strong>說明</strong>
        </th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            購物車商城系統
        </td>
        <td>
            $25,000
        </td>
        <td>
            替網站加裝購物車功能
            可免費任選智付寶或Paypal其中一項作為基本金流功能
        </td>
    </tr>
    <tr>
        <td>
            增加金流模組
        </td>
        <td>
            $3,000
        </td>
        <td>
            可加裝預設支援的金流模組
            <ul>
                <li>智付寶/智付通</li>
                <li>歐付寶</li>
                <li>Paypal</li>
            </ul>
        </td>
    </tr>
    <tr>
        <td>
            獨立開發金流模組
        </td>
        <td>
            $30,000起
        </td>
        <td>
            若要自行與銀行洽談金流服務，由於需要請工程師手工開發，則開發費用較高，每個項目 30,000 起，根據串接項目數量與困難度另行報價。(例: Web ATM 與 信用卡 為兩項)
        </td>
    </tr>
    <tr>
        <td>
            國際金流串接
        </td>
        <td>
            $100,000起
        </td>
        <td>
            若要與特殊國家金流簽約販售商品，不走 Paypal 等標準金流服務，則須支付國際金流串接開費用，另行報價。
        </td>
    </tr>
    <tr>
        <td>
            超商取貨模組
        </td>
        <td>
            $10,000
        </td>
        <td>
            與EZShip服務串接全家取貨付款等功能
        </td>
    </tr>
    <tr>
        <td>
            增加優惠與折扣規則
        </td>
        <td>
            $6,000起
        </td>
        <td>
            可根據需求規格增加多種優惠折扣，如免運、紅利、折價券、每三送一等等，每種項目6,000元
        </td>
    </tr>
    <tr>
        <td>
            會員與訂單匯出
        </td>
        <td>
            $4,000
        </td>
        <td>
            匯出為 Excel 方便製作報表
        </td>
    </tr>
    </tbody>
</table>