system:
    debug: 0
    timezone: 'UTC'
    error_reporting: -1
project:
    name: Allstars 星辰設計 - 專業網頁設計與雲端系統開發

# Which folders you want to generate (Array)
folders:
    - entries
    - media

# Plugin classes with namespace (Array)
plugins:
    - \Vaseman\Plugin\ConfigPlugin